config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :create] do
    member do
      get :followings
      get :followers
      get :bookmark_tasks
    end
  end
  
  resources :tasks, only: [:index, :create, :edit, :update, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :bookmarks, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  
  has_many :bookmarks, dependent: :destroy
  has_many :users, through: :bookmarks
  
  validates :content, presence: true, length: { maximum: 100 } #100文字制限
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 10 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :tasks
#relationships関連
  has_many :relationships
  #中間テーブルを経由して向こう側のモデルのfollowカラムを参照,followings命名
  has_many :followings, through: :relationships, source: :follow
  #reverses_of_relationship命名、Relationship参照、user_idをfollow_id
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  #中間テーブルを経由して向こう側のモデルのuserカラムを参照,followers命名
  has_many :followers, through: :reverses_of_relationship, source: :user
  
#bookmarks関連
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_tasks, through: :bookmarks, source: :task
  
#フォロー関連
  def follow(other_user)
    unless self == other_user   #フォローするuserが自分自身ではないかどうか
      self.relationships.find_or_create_by(follow_id: other_user.id)  #重複しない。find→Rモデルのインスタンス、見つからなければcreate
    end
  end
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end
  #フォローしていないかどうか確認する
  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def feed_tasks
    Task.where(user_id: self.following_ids + [self.id])
  end
  
#ブックマーク関連 
  def bookmark(task)
    self.bookmarks.find_or_create_by(task_id: task.id)
  end
  def unbookmark(task)
    bookmark = self.bookmarks.find_by(task_id: task.id)
    bookmark.destroy if bookmark
  end
  def bookmark_task?(task)
    self.bookmark_tasks.include?(task)
  end
    
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include Pagy::Backend
  
  private
  
  #ログイン要求(ここで定義して継承コントローラーで使う)
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_tasks = user.tasks.count
    @count_followings = user.followings.count
    @count_followers = user.followers.count
    @count_bookmark_tasks = user.bookmark_tasks.count
  end
  
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action  :require_user_logged_in
  
  def create
    task = Task.find(params[:task_id])
    current_user.bookmark(task)
    flash[:success] = 'タスクをブックマークしました'
    redirect_to request.referer
  end

  def destroy
    task = Task.find(params[:task_id])
    current_user.unbookmark(task)
    flash[:success] = 'ブックマークを解除しました'
    redirect_to request.referer
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :require_user_logged_in
    
  def create
    user = User.find(params[:follow_id])
    current_user.follow(user)
    flash[:success] = 'ユーザをふぉろーしました'
    redirect_to request.referer
  end

  def destroy
    user = User.find(params[:follow_id])
    current_user.unfollow(user)
    flash[:success] = 'ユーザのフォローを解除しました。'
    redirect_to request.referer
  end

end

app/controllers/sessions_controller.rb
# ログイン機能のコントローラー
class SessionsController < ApplicationController

  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました'
    render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  
  def index
    redirect_to user_path(current_user)
  end
  
  
  def create
    @user = current_user
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:success] = 'タスクの投稿に成功しました'
      redirect_to user_url(@user)
    else
      @pagy, @tasks = pagy(@user.feed_tasks.order(id: :desc))
      flash.now[:danger] = 'タスクの投稿に失敗しました。'
      render 'users/show'
    end
    
  end

  def edit
    @user = current_user
    @task = Task.find(params[:id])
  end

  def update
    @user = current_user
    @task = Task.find(params[:id])
    
    if @task.update(task_params)
      flash[:success] = 'タスクは正常に更新されました'
      redirect_to user_url(@user)
    else
      flash.now[:danger] = 'タスクは更新されませんでした'
      render :edit
    end
  end

  def destroy
    @task.destroy
    flash[:success]= 'タスクを削除しました'
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def task_params
    params.require(:task).permit(:content)
  end
  
  #ログインユーザーの投稿か確認する
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
    include SessionsHelper
  
  def index
    if logged_in?
       redirect_to user_url(current_user)
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :followings, :followers, :bookmark_tasks]
  
  def index
    @pagy, @users = pagy(User.order(id: :desc), items: 5)
  end

  def show
    @user = User.find(params[:id])
    if @user == current_user
      @pagy, @tasks = pagy(@user.feed_tasks.order(id: :desc))      
    else
      @pagy, @tasks = pagy(@user.tasks.order(id: :desc))
    end
    counts(@user)
    
    if logged_in?
      @task = current_user.tasks.build
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザーを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザーの登録に失敗しました。'
      render :new
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @pagy, @followings = pagy(@user.followings)
    counts(@user)
  end

  def followers
    @user = User.find(params[:id])
    @pagy, @followers = pagy(@user.followers)
    counts(@user)
  end
  
  def bookmark_tasks
    @user = User.find(params[:id])
    @task = Task.find(params[:id])
    @pagy, @bookmark_tasks = pagy(@user.bookmark_tasks)
    counts(@user)
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !!current_user #current_userのインスタンス有→false→true
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/bookmarks/_bookmark_button.html.erb
<% if current_user.bookmark_task?(task) %>
  <%= form_with(model: current_user.bookmarks.find_by(task_id: task.id), method: :delete) do |f| %>
    <%= hidden_field_tag :task_id, task.id, id: "task_#{task.id}" %>
<!--fontawesomeボタン-->      
      <%= button_tag type: 'submit', class: 'btn' do %>
        <i class="bi bi-bookmark-star-fill" style=""></i>
      <% end %>
  <% end %>
<% else %>
  <%= form_with(model: current_user.bookmarks.build) do |f| %>
    <%= hidden_field_tag :task_id, task.id, id: "task_#{task.id}" %>
<!--fontawesomeボタン-->
      <%= button_tag type: 'submit', class: 'btn' do %>
        <i class="bi bi-bookmark-star" style=""></i>
      <% end %>
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-secondary px-3">
    
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav mr-auto">
          <li><a class="navbar-brand" href="/">するコトめも</a></li>
      </ul>
    </div>

      <ul class="navbar-nav">
        <% if logged_in? %>
        <li class="mt-2 me-3 text-nowrap">
          ログインユーザー:　<%= current_user.name %>
        </li>
        <li>
          <%= link_to 'Logout', logout_path, method: :delete, class: 'btn btn-secondary border' %>
        </li>
        <% end %>
      </ul>

  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Surukoto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<!--bootstrap-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
<!--FontAwesome-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body data-turbolinks="false">
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_with(model: current_user.relationships.find_by(follow_id: user.id), method: :delete) do |f| %>
      <%= hidden_field_tag :follow_id, user.id, id: "follow_#{user.id}" %>
<!--fontawesomeボタン-->      
        <%= button_tag type: 'submit', class: 'btn' do %>
            <i class="bi bi-suit-heart-fill" style="font-size: 20px; color: red"></i>
        <% end %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id, id: "follow_#{user.id}" %>
<!--fontawesomeボタン-->
      <%= button_tag type: 'submit', class: 'btn' do %>
        <i class="bi bi-suit-heart" style="font-size: 20px; color: gray"></i>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/tasks/_tasks.html.erb
<% if tasks.any? %>
  <ul class="list-unstyled mt-2">
    <% tasks.each do |task| %>
      <li class="d-flex offset-1 mb-2">
<!--投稿ユーザーアイコン-->
        <img class="rounded me-2" src="<%= gravatar_url(task.user, { size: 40 }) %>" alt="">
<!--投稿ユーザー名-->
        <div class="col-2 mt-1">
          <%= task.user.name %>
        </div>
<!--ブックマークボタン-->
        <%= render 'bookmarks/bookmark_button', task: task %>
<!--タスク本文-->
        <div class="col-6 mt-1"><%= task.content %></div>
<!--編集ボタン-->
        <% if current_user == task.user %>
          <%= link_to(edit_task_path(task), class: 'btn') do %>
            <i class="bi bi-pencil-square"></i>
          <% end %>
        <% end %>

<!--削除ボタン-->
        <% if current_user == task.user %>
          <%= link_to(task, method: :delete, data: { confirm: "You sure?" } , class: 'btn') do %>
            <i class="bi bi-trash-fill"></i>
          <% end %>
        <% end %>
        
      </li>
    <% end %>
  </ul>
  <div class="d-flex justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<!--メニュー-->
<%= render 'users/menus', users: @users %>


<%= form_with(model: @task) do |f| %>
 <div class="form-group row justify-content-center">
   <div class="text-center p-3">
     <h3>編集ページ</h3>
    </div>
    <div class="col-sm-7">
      <%= f.text_field :content, class: "form-control" %>
    </div>
      <%= f.submit '編集', class: 'btn btn-primary col-sm-2' %>
  </div>

<% end %>

app/views/toppages/index.html.erb
<div class="row justify-content-center">
  <div class="text-center border border-secondary col-6 p-2 p-sm-5 my-4 rounded">
    
    <h2>するコトめも</h2>
    
    <div class="text-secondary p-3">
      <h5>家族がつながるアプリ</h5>
      <p>家族のするコトを共有して、忙しい家族の時間をサポートします。</p>
    </div>
    <div>
      <%= link_to(login_path, class: 'btn btn-secondary') do %>
        login
      <% end %>
    </div>
    <div class='m-2'>
      <%= link_to 'signup?', signup_path %>
    </div>
  </div>
</div>

app/views/users/_menus.html.erb
  <div class="row">
    <aside class="col-sm-3 mt-2">
      <div class="mb-3 d-flex">
        <img class="rounded-circle me-2" src="<%= gravatar_url(@user, { size: 32 }) %>" alt="">
        <div>
          <%= link_to @user.name, users_path %><% if current_user == @user %>（login）<% end %>
        </div>
       </div>
    </aside>
    <div class="col-sm-8">
      <ul class="nav nav-tabs justify-content-end mb-3">
        <li class="nav-item">
          <%= link_to(users_path, class: 'btn me-3 mt-1') do %>
            <i class="bi bi-person-fill"></i>ユーザー一覧
          <% end %>
        </li>
        <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">TODOリスト <span class="badge rounded-pill bg-secondary"><%= @count_tasks %></span></a></li>
        <li class="nav-item"><a href="<%= bookmark_tasks_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(bookmark_tasks_user_path(@user)) %>">★リスト <span class="badge rounded-pill bg-secondary"><%= @count_bookmark_tasks %></span></a></li>
        <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォローリスト <span class="badge rounded-pill bg-secondary"><%= @count_followings %></span></a></li>
        <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワーリスト <span class="badge rounded-pill bg-secondary"><%= @count_followers %></span></a></li>
      </ul>
    </div>
  </div>
 

app/views/users/_users.html.erb
<% if users.any? %>
  <ul>
    <% users.each do |user| %>
      <li class="mb-3 d-flex">
        
        <!--アバター-->
        <img class="rounded-circle" src="<%= gravatar_url(user, { size: 48 }) %>" alt="">

        <!--ユーザーネーム-->
        <div class="ms-2 mt-2">
          <%= link_to user.name, user_path(user) %>
        </div>
        
        <!--ログインユーザーのとき-->
        <% if user == current_user %>
        <div class="ms-2 mt-2">(ログインユーザー)</div>
        <% end %>


        <!--フォローボタン-->
        <div>
          <%= render 'relationships/follow_button', user: user %>
        </div>
        
      </li>
    <% end %>
  </ul>
  
<!--pagyをセンターに配置-->
  <div class="d-flex align-items-center justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>

<% end %>

app/views/users/bookmark_tasks.html.erb
<!--メニュー-->
  <%= render 'users/menus', users: @users %>

<%= render 'tasks/tasks', tasks: @bookmark_tasks %>

app/views/users/followers.html.erb
<!--メニュー-->
  <%= render 'users/menus', users: @users %>

<!--ユーザーリスト（フォロー）-->
  <div class="row justify-content-center">
    <div class="col-6">
      <%= render 'users', users: @followers %>
    </div>
  </div>

app/views/users/followings.html.erb
<!--メニュー-->
  <%= render 'users/menus', users: @users %>

<!--ユーザーリスト（フォロー）-->
  <div class="row justify-content-center">
    <div class="col-6">
      <%= render 'users', users: @followings %>
    </div>
  </div>

app/views/users/index.html.erb
  <div class="row justify-content-center">
    <div class="border border-secondary col-6 p-sm-5 my-4 rounded">

<!--ユーザー一覧-->
      <div class="text-center">
        <h5>ユーザ一覧</h5>
      </div>
      <%= render 'users', users: @users %>
  
  
    </div>
  </div>

app/views/users/new.html.erb
<div class="row justify-content-center border border-secondary rounded">

    <div class="text-center">
      <h1>Sign up</h1>
    </div>
    <div class="row justify-content-center">
      <div class="col-4">
    
        <%= form_with(model: @user) do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>
    
          <div class="mb-3">
            <%= f.label :name, 'Name' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
    
          <div class="mb-3">
            <%= f.label :email, 'Email' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>
    
          <div class="mb-3">
            <%= f.label :password, 'Password' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
    
          <div class="mb-3">
            <%= f.label :password_confirmation, 'Confirmation' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          
          <div class="row justify-content-center">
          <%= f.submit 'Sign up', class: 'btn btn-primary w-50' %>
          </div>

        <% end %>
        
        <div class="text-center mt-2">
          <%= link_to 'login?', login_path %>
        </div>
        
      </div>
    </div>
  </div>

app/views/users/show.html.erb
<!--メニュー-->
  <%= render 'users/menus', users: @users %>

<!--自分のページなら新規投稿フォームを設置する-->
  <% if current_user == @user %>
    <%= form_with(model: @task) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
     <div class="form-group row justify-content-center">
        <div class="col-sm-7">
          <%= f.text_field :content, class: "form-control", placeholder: "新しいタスク" %>
        </div>
           <%= f.submit '新規投稿', class: 'btn btn-primary col-sm-2' %>
      </div>
  <div class="border-top my-3"></div>
    <% end %>
  <% end %>

  
<!--タスク一覧を表示-->
    <%= render 'tasks/tasks', tasks: @tasks %>